server:
  port: 8080
spring:
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  servlet:
    multipart:
      max-file-size: 10MB
service:
  user-api-server: http://localhost:8080
cloud:
  aws:
    s3:
      bucket: moimmoim
    region:
      static: ap-northeast-2
cdn:
  domain: moimmoim.s3.ap-northeast-2.amazonaws.com
