spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  servlet:
    multipart:
      max-file-size: 10MB
cloud:
  aws:
    s3:
      bucket: moimmoim
    region:
      static: ap-northeast-2
cdn:
  domain: moimmoim.s3.ap-northeast-2.amazonaws.com