= TeamBuilder API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[overview]]
= Overview

[[overview-http-verbs]]
== HTTP verbs
Person-service tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.
|==
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PUT`
| Used to update an existing resource, full updates only

| `DELETE`
| Used to delete an existing resource
|==

[[overview-http-status-codes]]
== HTTP status codes
Person-service tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|==
| Status code | Usage

| `200 OK`
| Standard response for successful HTTP requests. The actual response will depend on the request method used. +
  In a GET request, the response will contain an entity corresponding to the requested resource. +
  In a POST request, the response will contain an entity describing or containing the result of the action.

| `201 Created`
| The request has been fulfilled and resulted in a new resource being created.

| `400 Bad Request`
| The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

| `401 Unauthorized`
| The request has not been applied because it lacks valid authentication credentials for the target resource.

| `403 Forbidden`
| The server understood the request but refuses to authorize it.

| `404 Not Found`
| The requested resource could not be found but may be available again in the future. Subsequent requests by the client are permissible.
|==

= Resources

== Authentication Code

=== 인증코드 생성
operation::/commons/post-common[snippets='http-request,request-fields,http-response,response-fields']

=== 인증코드 조회
operation::/commons/get-common[http-response,response-fields']


== User
=== 아이디 중복체크
operation::/users/get-checkId[snippets='http-request,request-parameters,http-response,response-fields']
=== 회원가입
operation::/users/post-signUp[snippets='http-request,request-fields,http-response,response-fields']
=== 로그인
operation::/users/post-signIn[snippets='http-request,request-parameters,http-response,response-fields']
=== 개인정보 변경
operation::/users/put-user[snippets='http-request,request-fields,http-response,response-fields']
=== 회원 전체리스트
operation::/users/list-users[snippets='http-request,http-response,response-fields']
=== 활동중인 회원 리스트
operation::/users/list-activated-users[snippets='http-request,http-response,response-fields']
=== 활성화
operation::/users/put-activate[snippets='http-request,request-parameters,http-response,response-fields']
=== 비활성화
operation::/users/put-deactivate[snippets='http-request,request-parameters,http-response,response-fields']
=== 전체비활성화
operation::/users/put-deactivate-all[snippets='http-request,http-response,response-fields']

== Auth
=== me
operation::/auth/get-me[snippets='http-request,http-response,response-fields']

== Idea
=== 아이디어 생성
operation::/ideas/post-idea[snippets='http-request,request-fields,http-response,response-fields']

=== 아이디어 조회
operation::/ideas/get-idea[snippets='http-request,path-parameters,http-response,response-fields']

=== 아이디어 목록
operation::/ideas/list-idea[snippets='http-request,http-response,response-fields']

=== 아이디어 수정
operation::/ideas/put-idea[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

=== 아이디어 투표
operation::/ideas/vote-idea[snippets='http-request,path-parameters,http-response,response-fields']

=== 아이디어 투표 (최신)
operation::/ideas/vote-ideas[snippets='http-request,request-parameters,http-response,response-fields']

=== 아이디어 삭제
operation::/ideas/delete-idea[snippets='http-request,path-parameters,http-response']

== Session
=== session 생성
operation::/sessions/post-session[snippets='http-request,request-fields,http-response,response-fields']

=== session 조회
operation::/sessions/get-session[snippets='http-request,path-parameters,http-response,response-fields']

=== 최신 session 조회
operation::/sessions/latest-session[snippets='http-request,http-response,response-fields']

=== session 수정
operation::/sessions/update-session[snippets='http-request,request-fields,path-parameters,http-response,response-fields']

=== session 삭제
operation::/sessions/delete-session[snippets='http-request,path-parameters,http-response']

== Person

=== Create Person
operation::/persons/post-person[snippets='http-request,request-fields,http-response,response-fields']

=== Get Person
operation::/persons/get-person[snippets='http-request,path-parameters,http-response,response-fields']

=== Put Person
operation::/persons/put-person[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== Paged Person list
operation::/persons/list-person[snippets='http-request,request-parameters,http-response,response-fields']